language: java
jdk: openjdk8

# Travis CI 를 어느 branch 가 push 될 때 수행할지 설정
branches:
  only: main

# gradle 통해 의존서을 받게 되면 해당 디렉토리에 cache 하여,
# 같은 의존성은 다음 배포 때부터 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

# branch 에 push 되었을 때 수행하는 명령어
script: "./gradlew clean build"

# 배포에 필요한 파일들만 archive 에 옮겨서 archive/archive.zip 파일로 만든다.
before_deploy:
  - mkdir -p archive
  - cp build/libs/*.jar archive/application.jar
  - cp -r ./.ebextensions archive/.ebextensions
  - cd archive
  - ls -al
  - zip -r archive.zip application.jar .ebextensions

deploy:
  provider: elasticbeanstalk
  zip_file: archive.zip # before_deploy에서 이미 archive로 이동한 상태(cd archive)라 현재 위치에서 archive.zip 전송
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "ap-northeast-2"
  app: "airbnb"
  env: "Airbnb-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-382240023058"  # S3 bucket name
  on:
    branch: main

after_deploy:
  - echo "Elastic Beanstalk 배포 진행중입니다."



# Travis CI 실행 완료 후 자동 알림 설정
notifications:
  email:
    recipients:
      - wsnam0418@gmail.com